### ISSUE TITLE
Portable Shebang for Non-System Python?

### ISSUE THREAD

**Issue by rusholme** [StackIQ/StackiAttrs#1]
Hi,

Minor suggestion, but changing the stacki_attrs.py shebang too:

#! /usr/bin/env python

would pick up the preferred python from the user's path rather than the default system installation. stacki_attrs.py initially failed for me due to the jinga2 dependancy. This which was missing from my untouched OSX system python but was present in my working installation.

See:
https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability

**Comment by bsanders** [comment]
Fair enough!

Commit a72bec0 changes this.
